POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento 2",
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/41ea2464-08ed-46eb-98e8-fe8487cd7a51/attendees
Content-Type: application/json

{
    "name": "Helcio Anicio",
    "email": "helci2@helcio.com"
}


###

GET http://localhost:3333/events/41ea2464-08ed-46eb-98e8-fe8487cd7a51


###

GET http://localhost:3333/attendees/4/badge